/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects/$id/index'
import { Route as ProjectsIdArchitectureRouteImport } from './routes/projects/$id/architecture'
import { Route as ProjectsIdBlueprintRouteImport } from './routes/projects/$id/blueprint'
import { Route as ProjectsIdBuildRouteImport } from './routes/projects/$id/build'
import { Route as ProjectsIdCanvasRouteImport } from './routes/projects/$id/canvas'
import { Route as ProjectsIdCodeRouteImport } from './routes/projects/$id/code'
import { Route as ProjectsIdExportsRouteImport } from './routes/projects/$id/exports'
import { Route as ProjectsIdRisksRouteImport } from './routes/projects/$id/risks'
import { Route as ProjectsIdTasksRouteImport } from './routes/projects/$id/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdArchitectureRoute = ProjectsIdArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdBlueprintRoute = ProjectsIdBlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdBuildRoute = ProjectsIdBuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdCanvasRoute = ProjectsIdCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdCodeRoute = ProjectsIdCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdExportsRoute = ProjectsIdExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdRisksRoute = ProjectsIdRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdTasksRoute = ProjectsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/architecture': typeof ProjectsIdArchitectureRoute
  '/projects/$id/blueprint': typeof ProjectsIdBlueprintRoute
  '/projects/$id/build': typeof ProjectsIdBuildRoute
  '/projects/$id/canvas': typeof ProjectsIdCanvasRoute
  '/projects/$id/code': typeof ProjectsIdCodeRoute
  '/projects/$id/exports': typeof ProjectsIdExportsRoute
  '/projects/$id/risks': typeof ProjectsIdRisksRoute
  '/projects/$id/tasks': typeof ProjectsIdTasksRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/architecture': typeof ProjectsIdArchitectureRoute
  '/projects/$id/blueprint': typeof ProjectsIdBlueprintRoute
  '/projects/$id/build': typeof ProjectsIdBuildRoute
  '/projects/$id/canvas': typeof ProjectsIdCanvasRoute
  '/projects/$id/code': typeof ProjectsIdCodeRoute
  '/projects/$id/exports': typeof ProjectsIdExportsRoute
  '/projects/$id/risks': typeof ProjectsIdRisksRoute
  '/projects/$id/tasks': typeof ProjectsIdTasksRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/architecture': typeof ProjectsIdArchitectureRoute
  '/projects/$id/blueprint': typeof ProjectsIdBlueprintRoute
  '/projects/$id/build': typeof ProjectsIdBuildRoute
  '/projects/$id/canvas': typeof ProjectsIdCanvasRoute
  '/projects/$id/code': typeof ProjectsIdCodeRoute
  '/projects/$id/exports': typeof ProjectsIdExportsRoute
  '/projects/$id/risks': typeof ProjectsIdRisksRoute
  '/projects/$id/tasks': typeof ProjectsIdTasksRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$id'
    | '/projects/new'
    | '/projects/'
    | '/projects/$id/architecture'
    | '/projects/$id/blueprint'
    | '/projects/$id/build'
    | '/projects/$id/canvas'
    | '/projects/$id/code'
    | '/projects/$id/exports'
    | '/projects/$id/risks'
    | '/projects/$id/tasks'
    | '/projects/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/new'
    | '/projects'
    | '/projects/$id/architecture'
    | '/projects/$id/blueprint'
    | '/projects/$id/build'
    | '/projects/$id/canvas'
    | '/projects/$id/code'
    | '/projects/$id/exports'
    | '/projects/$id/risks'
    | '/projects/$id/tasks'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/projects/$id'
    | '/projects/new'
    | '/projects/'
    | '/projects/$id/architecture'
    | '/projects/$id/blueprint'
    | '/projects/$id/build'
    | '/projects/$id/canvas'
    | '/projects/$id/code'
    | '/projects/$id/exports'
    | '/projects/$id/risks'
    | '/projects/$id/tasks'
    | '/projects/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/architecture': {
      id: '/projects/$id/architecture'
      path: '/architecture'
      fullPath: '/projects/$id/architecture'
      preLoaderRoute: typeof ProjectsIdArchitectureRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/blueprint': {
      id: '/projects/$id/blueprint'
      path: '/blueprint'
      fullPath: '/projects/$id/blueprint'
      preLoaderRoute: typeof ProjectsIdBlueprintRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/build': {
      id: '/projects/$id/build'
      path: '/build'
      fullPath: '/projects/$id/build'
      preLoaderRoute: typeof ProjectsIdBuildRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/canvas': {
      id: '/projects/$id/canvas'
      path: '/canvas'
      fullPath: '/projects/$id/canvas'
      preLoaderRoute: typeof ProjectsIdCanvasRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/code': {
      id: '/projects/$id/code'
      path: '/code'
      fullPath: '/projects/$id/code'
      preLoaderRoute: typeof ProjectsIdCodeRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/exports': {
      id: '/projects/$id/exports'
      path: '/exports'
      fullPath: '/projects/$id/exports'
      preLoaderRoute: typeof ProjectsIdExportsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/risks': {
      id: '/projects/$id/risks'
      path: '/risks'
      fullPath: '/projects/$id/risks'
      preLoaderRoute: typeof ProjectsIdRisksRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/tasks': {
      id: '/projects/$id/tasks'
      path: '/tasks'
      fullPath: '/projects/$id/tasks'
      preLoaderRoute: typeof ProjectsIdTasksRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface ProjectsIdRouteChildren {
  ProjectsIdArchitectureRoute: typeof ProjectsIdArchitectureRoute
  ProjectsIdBlueprintRoute: typeof ProjectsIdBlueprintRoute
  ProjectsIdBuildRoute: typeof ProjectsIdBuildRoute
  ProjectsIdCanvasRoute: typeof ProjectsIdCanvasRoute
  ProjectsIdCodeRoute: typeof ProjectsIdCodeRoute
  ProjectsIdExportsRoute: typeof ProjectsIdExportsRoute
  ProjectsIdRisksRoute: typeof ProjectsIdRisksRoute
  ProjectsIdTasksRoute: typeof ProjectsIdTasksRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdArchitectureRoute: ProjectsIdArchitectureRoute,
  ProjectsIdBlueprintRoute: ProjectsIdBlueprintRoute,
  ProjectsIdBuildRoute: ProjectsIdBuildRoute,
  ProjectsIdCanvasRoute: ProjectsIdCanvasRoute,
  ProjectsIdCodeRoute: ProjectsIdCodeRoute,
  ProjectsIdExportsRoute: ProjectsIdExportsRoute,
  ProjectsIdRisksRoute: ProjectsIdRisksRoute,
  ProjectsIdTasksRoute: ProjectsIdTasksRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
